trigger: none

variables:
- name: vmimageName
  value: "windows-latest"
- name: EnvironmentName
  value: 'dev'

pool:
  vmImage: $(vmImageName)

steps:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'ASHubServiceConnection'
    ScriptType: 'FilePath'
    ScriptPath: '.\scripts\Manage-Datalake-FileSystem-ACL-Permissions.ps1'
    ScriptArguments: '$(EnvironmentName)'
    azurePowerShellVersion: 'LatestVersion'