trigger: none

variables:
- name: vmimagename
  value: "windows-latest"
- name: EnvironmentName
  value: 'dev'

pool:
   name: Default

steps:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'HubServiceConnection'
    ScriptType: 'FilePath'
    ScriptPath: '.\scripts\test.ps1'
    ScriptArguments: '$(EnvironmentName)'
    azurePowerShellVersion: 'LatestVersion'
