trigger: none

variables:
- name: vmimageName
  value: "windows-latest"

pool:
  vmImage: $(vmImageName)

stages:

- template: 'deploy-pipeline.yml'
  parameters:
    stageId: "Deploy_to_Hub_Environment"
    env: "dev"
    environmentName: "cfs-fwd-hub"
    serviceConnection: "HubServiceConnection"
