trigger: none

variables:
- name: vmimageName
  value: "windows-latest"
- name: EnvironmentName
  value: 'dev'

pool:
  vmImage: $(vmImageName)

steps:
- task: PowerShell@2
  inputs:
    filePath: '.\scripts\test.ps1'
    arguments: '$(EnvironmentName)'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'ASHubServiceConnection'
    ScriptType: 'FilePath'
    ScriptPath: '.\scripts\test.ps1'
    ScriptArguments: '$(EnvironmentName)'
    azurePowerShellVersion: 'LatestVersion'