parameters:
- name: stageId
  type: string
- name: dependsOn
  type: object
  default: []
- name: env
  type: string
- name: environmentName
  type: string
- name: serviceConnection
  type: string


stages:

- stage: "${{ parameters.stageId }}"
  displayName: "Deploying to [${{upper(parameters.env)}}] Environment"
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - deployment: Deploy
    displayName: "Deploying Bicep Template"
    environment: ${{parameters.environmentName}}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: ${{ parameters.serviceConnection }}
              ScriptType: 'FilePath'
              ScriptPath: '.\scripts\Manage-Datalake-FileSystem-ACL-Permissions.ps1'
              ScriptArguments: ${{parameters.environmentName}}
              azurePowerShellVersion: 'LatestVersion'
